import Head from "next/head";
import Navbar from "components/Navbar";

export default function AppLayout({ children }) {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/julian-logo.svg" />
      </Head>
      <main>
        <Navbar />
        {children}
      </main>
      {/* <style jsx>{styles}</style> */}
    </>
  );
}
