import Head from "next/head";
import Navbar from "components/Navbar";

export default function AppLayout({ children }) {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/julian-logo.svg" />
      </Head>

      <Navbar />
      <main>{children}</main>

      <style jsx>{`
         {
        }
      `}</style>
    </div>
  );
}
